### ISSUE TITLE
Packages are named poorly

### ISSUE THREAD

**Issue by Everspace** [Valkryst/Dynamic_Dialog_System#1]
The packages should be namespaced better. `handler`, `data` and `data.collection` are really poor choices for package names when presenting yourself as a library.

**Comment by Valkryst** [comment]
Do you have suggestions for what they could be renamed to or how the various classes could be better organized?

**Comment by Everspace** [comment]
Typically java packages are named based on the domain name it's coming from (in reverse order). This helps because domains are generally unique. You'll see a lot of `com.websitename`.

It could be as simple as `dds.data` or `dds.handler`, but it shouldn't be just `data`, because the end user might have a `data` package, and you wouldn't want there to be collisions when someone else defines `data.rule`.

**Comment by Valkryst** [comment]
Gotcha, I've pushed an update with some package alterations. Everything is now located under `com.valkryst.dds.*` with a `collection`, `manager`, and `object`package beneath that.

Does this seem alright to you, or would you suggest additional changes?
